export const featuredPhotos = [
    {
        name: "featured",
        price: 5,
        src: "featured/stock.jpeg"
    },
    {
        name: "featured 1",
        price: 5,
        src: "featured/w1.jpg"
    },
    {
        name: "featured 2",
        price: 5,
        src: "featured/w2.jpg"
    },
    {
        name: "featured 3",
        price: 5,
        src: "featured/w3.jpg"
    },
    {
        name: "featured 4",
        price: 5,
        src: "featured/w4.jpg"
    },
    {
        name: "featured 5",
        price: 5,
        src: "featured/w5.jpg"
    },
    {
        name: "featured 6",
        price: 5,
        src: "featured/w6.jpg"
    },
]

export const categories = [
    {
        name: "Architecture",
        url: "architecture",
        src: "categories/architecture.jpg",
        images: [
            {
                id: 'architecture1',
                name: 'Spiral',
                src: 'categories/architecture.jpg',
                description: 'Picture of spiralling architecture.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'architecture2',
                name: "Fogo Inn",
                src: 'categories/architecture/fogoinn.jpg',
                description: `Picture of Fogo Inn.`,
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'architecture3',
                name: "Arthur's",
                src: 'categories/architecture/arthurs.jpg',
                description: `Picture of Arthur's retail building.`,
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'architecture4',
                name: "Long Studio",
                src: 'categories/architecture/longstudio.jpg',
                description: `Picture of Long Studio building.`,
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'architecture5',
                name: "Long Studio 2",
                src: 'categories/architecture/longstudio2.jpg',
                description: `Picture of Long Studio (second angle).`,
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'architecture6',
                name: "Pine Sanctuary",
                src: 'categories/architecture/pinesanctuary.jpg',
                description: `Picture of Pine Sanctuary.`,
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'architecture7',
                name: "Squish Studio",
                src: 'categories/architecture/squishstudio.jpg',
                description: `Picture of Squish Studio.`,
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'architecture8',
                name: "Tower Studio",
                src: 'categories/architecture/towerstudio.jpg',
                description: `Picture of Tower Studio.`,
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'architecture9',
                name: "Faculty Building",
                src: 'categories/architecture/facultybuilding.jpg',
                description: `Picture of Faculty Building.`,
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'architecture10',
                name: "Vodaphone Building",
                src: 'categories/architecture/vodaphone.jpg',
                description: `Picture of Vodaphone Building.`,
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
        ]
    },
    {
        name: "Nature",
        url: "nature",
        src: "categories/nature.jpg",
        images: [
            {
                id: 'nature1',
                name: 'Flower and ladybugs',
                src: 'categories/nature.jpg',
                description: 'Picture of ladybugs in flower.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'nature2',
                name: 'Cosmo',
                src: 'categories/nature/cosmo.jpg',
                description: 'Picture of cosmo.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'nature3',
                name: 'Dancing Olivia',
                src: 'categories/nature/dancingolivia.jpg',
                description: 'Picture of Dancing Olivia.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'nature4',
                name: 'Double Exposure',
                src: 'categories/nature/doubleexposure.jpg',
                description: 'Picture of Double Exposure.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'nature5',
                name: 'Everyone Loves Rose',
                src: 'categories/nature/everyonelovesrose.jpg',
                description: 'Everyone Loves Rose.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'nature6',
                name: 'Dark Flowers',
                src: 'categories/nature/flowersdark.jpg',
                description: 'Picture of dark flowers.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'nature7',
                name: 'Glowing Sunflower',
                src: 'categories/nature/glowingsunflower.jpg',
                description: 'Picture of glowing sunflower.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'nature8',
                name: 'Happy Garden',
                src: 'categories/nature/happygarden.jpg',
                description: 'Picture of a happy garden.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'nature9',
                name: 'Ladybug in Poppy',
                src: 'categories/nature/ladybuginpoppy.jpg',
                description: 'Picture of a ladybug in poppy.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'nature10',
                name: "Let's Dance",
                src: 'categories/nature/letsdance.jpg',
                description: 'Dance away.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'nature11',
                name: "Painted Flower",
                src: 'categories/nature/paintedflower.jpg',
                description: 'Picture of painted flower.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'nature12',
                name: "Poppies and Dragonfly",
                src: 'categories/nature/poppiesanddragonfly.jpg',
                description: 'Picture of dragonflies in poppy.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
        ]
    },
    {
        name: "Creative",
        url: "creative",
        src: "categories/creative.jpg",
        images: [
            {
                id: 'creative1',
                name: "Creative",
                src: 'categories/creative.jpg',
                description: 'Picture of creative.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'creative2',
                name: "Ada",
                src: 'categories/creative/ada.jpg',
                description: 'Picture of Ada.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'creative3',
                name: "Ada 2",
                src: 'categories/creative/ada1.jpg',
                description: 'Picture of Ada (second angle).',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'creative4',
                name: "City Hall",
                src: 'categories/creative/cityhall.jpg',
                description: 'Picture of city hall.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'creative5',
                name: "Cyclers Art",
                src: 'categories/creative/cyclersart.jpg',
                description: 'Picture of cyclers.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'creative6',
                name: "Dancing Under The Moon",
                src: 'categories/creative/dancingunderthemoon.jpg',
                description: 'Picture of dancing under the moon.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'creative7',
                name: "Fish Is Coming To Town",
                src: 'categories/creative/fishiscomingtotown.jpg',
                description: 'Picture of fish coming to town.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'creative8',
                name: "Impression",
                src: 'categories/creative/impression.jpg',
                description: 'Picture of Impression.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'creative9',
                name: "In The Center",
                src: 'categories/creative/inthecentre.jpg',
                description: 'Picture of in the center.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'creative10',
                name: "Joyful",
                src: 'categories/creative/joyful.jpg',
                description: 'Picture of joyful.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'creative11',
                name: "Light",
                src: 'categories/creative/light.jpg',
                description: 'Picture of light.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'creative12',
                name: "Light Blue",
                src: 'categories/creative/lightblur.jpg',
                description: 'Picture of light blur.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'creative13',
                name: "Light Paint",
                src: 'categories/creative/lightpaint.jpg',
                description: 'Picture of light paint.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'creative14',
                name: "Looking Through",
                src: 'categories/creative/lookingthrough.jpg',
                description: 'Picture of looking through.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'creative15',
                name: "On The beach",
                src: 'categories/creative/onthebeach.jpg',
                description: 'Picture of beach.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'creative16',
                name: "People Blur",
                src: 'categories/creative/peopleblur.jpg',
                description: 'Picture of people blur.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'creative17',
                name: "Street Car",
                src: 'categories/creative/streetcar.jpg',
                description: 'Picture of streetcar.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'creative18',
                name: "Street Car 2",
                src: 'categories/creative/streetcar1.jpg',
                description: 'Picture of streetcar (second angle).',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'creative19',
                name: "Tram Panning",
                src: 'categories/creative/trampanning.jpg',
                description: 'Picture of tram panning.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'creative20',
                name: "Winter Blur",
                src: 'categories/creative/winterblur.jpg',
                description: 'Picture of winter blur.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
        ]
    },
    {
        name: "Landscape",
        url: "landscape",
        src: "categories/landscape.jpg",
        images: [
            {
                id: 'landscape',
                name: "Landscape",
                src: 'categories/landscape.jpg',
                description: 'Picture of landscape.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'landscape1',
                name: "By The Iceberg",
                src: 'categories/landscape/bytheiceburg.jpg',
                description: 'Picture of iceburg.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'landscape2',
                name: "Fall Colors",
                src: 'categories/landscape/fallcolors.jpg',
                description: 'Picture of fall colors.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'landscape3',
                name: "Fall Color Touch",
                src: 'categories/landscape/fallcolortouch.jpg',
                description: 'Picture of fall color touch.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'landscape4',
                name: "Good Morning",
                src: 'categories/landscape/goodmorning.jpg',
                description: 'Picture of a good morning.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'landscape5',
                name: "Little Red Cabin",
                src: 'categories/landscape/littleredcabin.jpg',
                description: 'Picture of a little red cabin.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'landscape6',
                name: "Morning Sephia",
                src: 'categories/landscape/morningsephia.jpg',
                description: 'Picture of a sephia morning.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'landscape7',
                name: "Potts Falls",
                src: 'categories/landscape/pottsfalls.jpg',
                description: 'Picture of potts falls.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'landscape8',
                name: "The Long Iceberg",
                src: 'categories/landscape/thelongiceberg.jpg',
                description: 'Picture of the long iceberg.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
        ]
    },
    {
        name: "Street",
        url: "street",
        src: "categories/street.jpg",
        images: [
            {
                id: 'street',
                name: "Street",
                src: 'categories/street.jpg',
                description: 'Picture of people on street.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'street1',
                name: "Busy Street",
                src: 'categories/street/busystreet.jpg',
                description: 'Picture of a busy street.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'street2',
                name: "By The River",
                src: 'categories/street/byriver.jpg',
                description: 'Picture by the river.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'street3',
                name: "Cross Over",
                src: 'categories/street/crossover.jpg',
                description: 'Picture of crossover.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'street4',
                name: "Golden Hour",
                src: 'categories/street/goldenhour.jpg',
                description: 'Picture of golden hour.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'street5',
                name: "Running On Rooftop",
                src: 'categories/street/runningrooftop.jpg',
                description: 'Picture of running rooftop.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'street6',
                name: "Sephia Place",
                src: 'categories/street/sephiaplace.jpg',
                description: 'Picture of a sephia place.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'street7',
                name: "Street Photo",
                src: 'categories/street/streetphoto.jpg',
                description: 'Street photo.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'street8',
                name: "The View",
                src: 'categories/street/theview.jpg',
                description: 'Picture of the view.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            
            {
                id: 'street10',
                name: "Up",
                src: 'categories/street/up.jpg',
                description: 'Up.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'street11',
                name: "Window Reflections",
                src: 'categories/street/windowreflections.jpg',
                description: 'Picture of window reflections.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'street12',
                name: "Yellow",
                src: 'categories/street/yellow.jpg',
                description: 'Picture of yellow.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'street9',
                name: "Time To Go Home",
                src: 'categories/street/timetogohome.jpg',
                description: 'Picture of time to go home.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'street13',
                name: "Yellow House",
                src: 'categories/street/yellowhouse.jpg',
                description: 'Picture of yellow house.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
        ]
    },
    {
        name: "Wildlife",
        url: "wildlife",
        src: "categories/wildlife.jpg",
        images: [
            {
                id: 'wildlife',
                name: "Wildlife",
                src: 'categories/wildlife.jpg',
                description: 'Picture of yellow house.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'wildlife1',
                name: "Bird's Back",
                src: 'categories/wildlife/birdback.jpg',
                description: 'Picture of bird.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'wildlife2',
                name: "Bird Huddle",
                src: 'categories/wildlife/birdhuddle.jpg',
                description: 'Picture of bird.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'wildlife3',
                name: "Bird Island",
                src: 'categories/wildlife/birdisland.jpg',
                description: 'Picture of bird.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'wildlife4',
                name: "Commotion",
                src: 'categories/wildlife/commotion.jpg',
                description: 'Picture of bird.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'wildlife5',
                name: "Cozy",
                src: 'categories/wildlife/cozy.jpg',
                description: 'Picture of bird.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'wildlife6',
                name: "Cute Face",
                src: 'categories/wildlife/cuteface.jpg',
                description: 'Picture of bird.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'wildlife7',
                name: "Enjoy Food",
                src: 'categories/wildlife/enjoyfood.jpg',
                description: 'Picture of bird.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'wildlife8',
                name: "Happy Meal",
                src: 'categories/wildlife/happymeal.jpg',
                description: 'Picture of bird.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'wildlife9',
                name: "In The Field",
                src: 'categories/wildlife/inthefield.jpg',
                description: 'Picture of bird.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'wildlife10',
                name: "Lullabby",
                src: 'categories/wildlife/lullaby.jpg',
                description: 'Picture of bird.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'wildlife11',
                name: "Morning Call",
                src: 'categories/wildlife/morningcall.jpg',
                description: 'Picture of bird.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'wildlife16',
                name: "Proposal",
                src: 'categories/wildlife/puffing1.jpg',
                description: 'Picture of bird.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'wildlife17',
                name: "I Am Coming",
                src: 'categories/wildlife/puffing2.jpg',
                description: 'Picture of bird.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'wildlife12',
                name: "Motherhood",
                src: 'categories/wildlife/motherhood.jpg',
                description: 'Picture of bird.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'wildlife13',
                name: "Red Bird",
                src: 'categories/wildlife/redbird.jpg',
                description: 'Picture of bird.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'wildlife14',
                name: "Swans",
                src: 'categories/wildlife/swans.jpg',
                description: 'Picture of bird.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            },
            {
                id: 'wildlife15',
                name: "Yellowbird",
                src: 'categories/wildlife/yellowbird.jpg',
                description: 'Picture of bird.',
                price: '$5',
                purchaseLink: 'http://stripe.com',
            }
        ]
    }
]

export const mainFeaturePics = [
    {
        id: 1,
        alt: "Man holding child photo",
        src: "mainfeatures/feature1.jpg",
        price: '$20',
        direction: "right",
        description: "Description about photo. Description about photo. Description about photo.",
        buyLink: "#"
    },
    {
        id: 2,
        alt: "Horse racing photo",
        src: "mainfeatures/feature2.jpg",
        direction: "left",
        price: '$30',
        description: "Description about photo. Description about photo. Description about photo.",
        buyLink: "#"
    },
    {
        id: 3,
        alt: "Swans/ducks photo",
        src: "mainfeatures/feature3.jpg",
        direction: "right",
        price: '$40',
        description: "Description about photo. Description about photo. Description about photo.",
        buyLink: "#"
    },
    {
        id: 4,
        alt: "Red cabin",
        src: "mainfeatures/redcabin.jpg",
        direction: "left",
        price: '$9',
        description: "Description about photo. Description about photo. Description about photo.",
        buyLink: "#"
    },
]